// src/constants/permissions.js
export const PERMISSIONS = {
  PROJECT_CREATE: "PROJECT_CREATE",
  PROJECT_DELETE: "PROJECT_DELETE",

  TASK_CREATE: "TASK_CREATE",
  TASK_ASSIGN: "TASK_ASSIGN",
  TASK_UPDATE_STATUS: "TASK_UPDATE_STATUS",

  USER_INVITE: "USER_INVITE"
};
